FROM ubuntu:18.04

RUN apt-get update && apt-get install -y vim wget curl git

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -O ~/miniconda.sh
RUN bash ~/miniconda.sh -b -p /miniconda
ENV PATH="/miniconda/bin:$PATH"

RUN conda install -y -c ome python=3.6 zeroc-ice36-python omero-py
RUN pip install jupyter pyyaml

COPY . /multiplex-imaging-pipeline

CMD /bin/bash
